name: StatsDB
version: 1.4
author: GiantTree
main: net.groundmc.statsdb.StatsDB

commands:
  statsdb:
    description: StatsDB
    permission: statsdb.admin
    usage: /<command> <statistic> [material|entity|player] [player]

permissions:
  statsdb.admin:
    description: Grants administrative access to this plugin
    default: op
