name: StatsDB
version: ${env.GIT_COMMIT}
author: GiantTreeLP
main: gtlp.groundmc.statsdb.StatsDB
depend: [GroundMCKotlinLoader]

commands:
  statsdb:
    description: StatsDB
    permission: statsdb.admin
    usage: /<command> <statistic> [material|entity|player]

permissions:
  statsdb.admin:
    description: Grants administrative access to this plugin
    default: op
